. .\Scripts\Active-Processes.ps1
. .\Scripts\Advanced-Menu.ps1
. .\Scripts\AmCache.ps1
. .\Scripts\Browser-Cookies.ps1
. .\Scripts\Browser-History.ps1
. .\Scripts\DLLs.ps1
. .\Scripts\Event-Logs.ps1
. .\Scripts\File-Associations.ps1
. .\Scripts\Image-Disk.ps1
. .\Scripts\Image-RAM.ps1
. .\Scripts\Image-Scan.ps1
. .\Scripts\Installed-Programs.ps1
. .\Scripts\Jump-List.ps1
. .\Scripts\KeyWord-Search.ps1
. .\Scripts\LNK-Files.ps1
. .\Scripts\Logging.ps1
. .\Scripts\MRU-Info.ps1
. .\Scripts\Net-Connection-Profiles.ps1
. .\Scripts\OneForAll.ps1
. .\Scripts\Packet-Capture.ps1
. .\Scripts\Peripheral-Devices.ps1
. .\Scripts\Prefetch-Files.ps1
. .\Scripts\Record-Registry.ps1
. .\Scripts\Record-User-Actions.ps1
. .\Scripts\Recycle-Bin.ps1
. .\Scripts\Remote-Desktop.ps1
. .\Scripts\SRUM-Info.ps1
. .\Scripts\Scan-Registry.ps1
. .\Scripts\Scheduled-Tasks.ps1
. .\Scripts\Screenshot.ps1
. .\Scripts\Set-Output-Location.ps1
. .\Scripts\Shellbags.ps1
. .\Scripts\ShimCache.ps1
. .\Scripts\Startup-Items.ps1
. .\Scripts\Swap-Files.ps1
. .\Scripts\System-Info.ps1
. .\Scripts\System-Restore-Points.ps1
. .\Scripts\System-Services.ps1
. .\Scripts\Timezone-Info.ps1
. .\Scripts\User-Accounts.ps1
. .\Scripts\User-Assist-Info.ps1
. .\Scripts\User-Profiles.ps1
. .\Scripts\OutputLocation.ps1
. .\Scripts\CopyToOutputDir.ps1